ыы
y0f0/test-kysect pull request #1
Opened 2021-07-06 15:18 UTC by y0f0

ыыы

2021-07-06 16:04 UTC, annchous requested changes
Пока так. И замечание по неймингу самого пулл-реквеста: "ыы" - как-то совсем не серьёзно) Можно было бы назвать хотя бы так же, как проект, но точно не так)

2021-07-06 16:04 UTC, annchous commented on test-kysect/Task.cs
> +        public string GetInformation()
Для подобного рода вещей можно сделать перегрузку стандартного метода ToString (он есть у всех классов). Тогда можно будет вообще не вызывать метод и просто писать Console.WriteLine(task) и получать отформатированный по-твоему вывод)
Подробнее как это сделать: https://docs.microsoft.com/bs-latn-ba/dotnet/csharp/programming-guide/classes-and-structs/how-to-override-the-tostring-method

2021-07-06 16:04 UTC, annchous commented on test-kysect/Task.cs
> +            this.Id = int.Parse(id);
Здесь this не нужен, ибо в классе у тебя Id с большой буквы, а в аргументах метода id с маленькой - они не спутаются)

2021-07-06 17:48 UTC, y0f0 commented on test-kysect/Program.cs
> +                if (command == "/add")
Не люблю свитчи

2021-07-06 17:51 UTC, y0f0 commented on test-kysect/Commands.cs
> +            UncompletedTasks.Add(task);
Сначала не было свойства Completed в Task. А потом убрать два листа было лень. И подумал, что так удобней с листами писать и читать код.

2021-07-06 18:05 UTC, I-SER-I commented on test-kysect/Program.cs
> +                if (command == "/add")
switch expression увидишь - полюбишь

2021-07-06 18:12 UTC, y0f0 commented on test-kysect/Program.cs
> +            while (true)
А смысл еще один класс в котором будет один метод на 100 строк (while true и т.д.) ?

2021-07-06 18:27 UTC, y0f0 commented on test-kysect/Program.cs
> +                if (command == "/add")
> switch expression увидишь - полюбишь

ненужный синтаксический сахар

2021-07-06 18:30 UTC, I-SER-I commented on test-kysect/Program.cs
> +                if (command == "/add")
ладно.

2021-07-06 18:44 UTC, annchous commented on test-kysect/Program.cs
> +                if (command == "/add")
> Не люблю свитчи

Но так ты постоянно повторяешь кусок кода `else if (command == `  и ещё о кавычки добавляешь, что делает твой код намного длиннее, но не добавляет какого-то удобства или изящности.

Просто сравни
```csharp
else if (command == "/save")
{
    commandsHandler.Save(parsedLine[1]); 
}
else if (command == "/load")
{
    commandsHandler.Load(parsedLine[1]);
}
```
и
```csharp
case ("/save")
    commandsHandler.Save(parsedLine[1]); 
    break;
case ("/load")
    commandsHandler.Load(parsedLine[1]);
    break;
```

2021-07-07 06:01 UTC, y0f0 commented on test-kysect/Program.cs
> +                if (command == "/add")
>Но так ты постоянно повторяешь кусок кода else if (command == и ещё о кавычки добавляешь, что делает твой код намного длиннее, но не добавляет какого-то удобства или изящности.

Согласен, но в switch-конструкциях еще нужно не забывать про break + еще одна строчка. Всегда про него забываю.

2021-07-07 07:12 UTC, FrediKats commented on test-kysect/Program.cs
> +            while (true)
@y0f0 на этот вопрос тебе ответит Вайсфельд.

2021-07-07 07:13 UTC, FrediKats commented on test-kysect/Program.cs
> +                if (command == "/add")
> нужно не забывать про break

@y0f0 Напиши так, чтобы работало без брейка.

2021-07-07 07:13 UTC, FrediKats commented on test-kysect/Program.cs
> +                if (command == "/add")
(спойлер: когда в кейсе делается reutrn, то не нужен брейк)

2021-07-07 08:15 UTC, y0f0 commented on test-kysect/Program.cs
> +                if (command == "/add")
> (спойлер: когда в кейсе делается reutrn, то не нужен брейк)

Так все равно return писать то же самое

2021-07-07 08:19 UTC, y0f0 commented on test-kysect/Program.cs
> +                if (command == "/add")
А новые c# 8 expression явно не для этого предназначены 
`var result = something switch {`
`     "a" => 1,`
`    "b" => 2,`
`     _ => 3`
`}`

2021-07-07 08:35 UTC, FrediKats commented on test-kysect/Program.cs
> +                if (command == "/add")
А что значит не для этого? У тебя есть механизм сопоставления. И ты так-то его и делашь. Есть строка, ей сопоставляется какая-то команда. Почему бы тогда не сделать:
```
var command = arg switch {
"first" => new FirstCommand(args),
"second" => new SecondCommand(args)
}

command.Execute();
```

2021-07-07 08:44 UTC, y0f0 commented on test-kysect/Program.cs
> +                if (command == "/add")
> А что значит не для этого? У тебя есть механизм сопоставления. И ты так-то его и делашь. Есть строка, ей сопоставляется какая-то команда. Почему бы тогда не сделать:
> 
> ```
> var command = arg switch {
> "first" => new FirstCommand(args),
> "second" => new SecondCommand(args)
> }
> 
> command.Execute();
> ```

Не сделать, так как try catch туда не засунешь (где new FirstCommand(args),)

2021-07-07 08:46 UTC, y0f0 commented on test-kysect/Program.cs
> +                if (command == "/add")
ну или если все переделать тогда можно

2021-07-07 09:49 UTC, annchous commented
Суть пулл-реквеста в том, что ты из какой-то специально выделенной под какую-то часть работы ветки вливаешь изменения в мастер - основную ветку. У тебя сейчас какой-то обратный ход: пулл-реквест из master в my-branch. Чтобы исправить это, можешь переименовать master в dev, а my-branch в master (в такой последовательности).
![image](https://user-images.githubusercontent.com/57408376/124738560-b6e04d00-df21-11eb-892c-3d11a941861c.png)
(как это у тебя сейчас)

2021-07-07 10:02 UTC, closed without merging